spring.application.name=papopago-fintech

# Endereço do banco de dados
spring.datasource.url=${DB_URL_PP}

# Usuário do banco de dados
spring.datasource.username=${DB_USER_PP}

# Senha do banco de dados
spring.datasource.password=${DB_PASSWORD_PP}

# Mostrar as instruções SQL
# executadas no banco de dados
spring.jpa.show-sql=true
